// Real, verified photography isn't available for every one of the ~50 image
// slots this site needs (marble collection identities, colour swatches,
// blog thumbnails, etc.). Rather than guess at more stock-photo URLs — which
// is how the site ended up with the same handful of images duplicated
// everywhere — slots without a confirmed photo render an original abstract
// stone pattern instead: deterministic per seed, drawn in the brand palette,
// and never identical to another slot. It reads as intentional art
// direction rather than a placeholder.

function mulberry32(seed) {
  let a = seed;
  return function () {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function hashSeed(str) {
  let h = 0;
  for (let i = 0; i < str.length; i++) {
    h = (Math.imul(31, h) + str.charCodeAt(i)) | 0;
  }
  return Math.abs(h) || 1;
}

// Curated tone palettes — each maps to a believable stone family, always
// drawn from the site's own colour tokens plus a few true stone hues.
const TONES = {
  ivory: { base: ["#EDE6D6", "#F6F1E5", "#E2D8C2"], vein: "#A47245", grain: "#C9BFA4" },
  bianco: { base: ["#F5F2EA", "#FAF8F2", "#E9E3D4"], vein: "#8B8272", grain: "#D8D2C2" },
  grigio: { base: ["#C9C4B8", "#DAD5C8", "#B3ADA0"], vein: "#5C574C", grain: "#8B8272" },
  basalt: { base: ["#221F19", "#2E2A22", "#161310"], vein: "#7C5230", grain: "#3B362C" },
  moss: { base: ["#28321F", "#37432A", "#1D2417"], vein: "#8FA377", grain: "#4C5B3C" },
  ocean: { base: ["#1E2E38", "#28414F", "#152229"], vein: "#6E97A8", grain: "#3A5563" },
  terra: { base: ["#5A3B27", "#71492E", "#432A1B"], vein: "#C79760", grain: "#8C5E3A" },
  rosa: { base: ["#D9BFB2", "#E7D2C6", "#C7A997"], vein: "#A6674D", grain: "#BE9482" },
  rosso: { base: ["#5B211A", "#742C22", "#421811"], vein: "#B4785A", grain: "#6F2F24" },
  sand: { base: ["#D8C6A3", "#E8DAB8", "#C4AE84"], vein: "#8C6A45", grain: "#B39B6E" },
  bronze: { base: ["#8C6A45", "#A47B4F", "#71542F"], vein: "#F4EFE4", grain: "#5F4830" },
};

function buildVeins(rng, w, h, count, color, opacity) {
  let paths = "";
  for (let i = 0; i < count; i++) {
    const startX = rng() * w;
    const startY = -20;
    let x = startX;
    let y = startY;
    let d = `M ${x.toFixed(1)} ${y.toFixed(1)} `;
    const steps = 5 + Math.floor(rng() * 4);
    for (let s = 0; s < steps; s++) {
      x += (rng() - 0.5) * w * 0.5;
      y += (h + 40) / steps;
      d += `Q ${(x + (rng() - 0.5) * 60).toFixed(1)} ${(y - 20).toFixed(1)}, ${x.toFixed(1)} ${y.toFixed(1)} `;
    }
    const width = (0.6 + rng() * 1.8).toFixed(2);
    paths += `<path d="${d}" stroke="${color}" stroke-width="${width}" fill="none" opacity="${(opacity * (0.5 + rng() * 0.6)).toFixed(2)}" stroke-linecap="round" />`;
  }
  return paths;
}

export default function StoneSwatch({ tone = "ivory", seed = "default", className = "" }) {
  const palette = TONES[tone] || TONES.ivory;
  const rng = mulberry32(hashSeed(String(seed) + tone));
  const w = 400;
  const h = 400;

  const gradId = `g-${tone}-${hashSeed(String(seed))}`;
  const angle = Math.floor(rng() * 360);

  const grainSpecks = Array.from({ length: 26 }).map((_, i) => {
    const cx = (rng() * w).toFixed(1);
    const cy = (rng() * h).toFixed(1);
    const r = (0.6 + rng() * 2.2).toFixed(2);
    const op = (0.15 + rng() * 0.35).toFixed(2);
    return `<circle cx="${cx}" cy="${cy}" r="${r}" fill="${palette.grain}" opacity="${op}" />`;
  }).join("");

  const veinMarkup =
    buildVeins(rng, w, h, 4, palette.vein, 0.55) + buildVeins(rng, w, h, 3, palette.grain, 0.3);

  return (
    <svg
      viewBox={`0 0 ${w} ${h}`}
      preserveAspectRatio="xMidYMid slice"
      className={className}
      role="img"
      aria-hidden="true"
    >
      <defs>
        <linearGradient id={gradId} gradientTransform={`rotate(${angle} 0.5 0.5)`}>
          <stop offset="0%" stopColor={palette.base[0]} />
          <stop offset="55%" stopColor={palette.base[1]} />
          <stop offset="100%" stopColor={palette.base[2]} />
        </linearGradient>
      </defs>
      <rect width={w} height={h} fill={`url(#${gradId})`} />
      {/* Vein paths and grain specks are generated as raw SVG markup strings
          (see buildVeins above) — injected via dangerouslySetInnerHTML
          rather than as JSX children, since React otherwise escapes string
          content as text instead of parsing it as markup. The strings are
          entirely generated by this component, not user input. */}
      <g dangerouslySetInnerHTML={{ __html: grainSpecks }} />
      <g dangerouslySetInnerHTML={{ __html: veinMarkup }} />
      <rect width={w} height={h} fill="black" opacity="0.03" />
    </svg>
  );
}
